### PR TITLE
Few changes

### PR DESCRIPTION
**Pull request by the-lay**
Few changes:
- Overlap spinbox step is now 0.01 - by default it's 1.0, but I think percentage makes more sense
- Added tiling shape next to preview checkbox - gets updates whenever parameters change
- Removed irregular tiling mode - it's unsupported by napari anyway

tiler

### CODE REVIEW

**Comment by the-lay** [comment]
BTW, I am also planning to update `tiler.get_tile_bbox_position()` to also return all four vertices, not just two opposite vertices. With this it should be possible to make tiling preview in 3d easily, but this can be a different pull request.

**Comment by tdmorello** [comment]
Love the tiling shape you added!

Setting the spinbox stepsize to 0.01 is a good idea. I see a bug in this implementation where the up and down arrows won't change the value when the number is > 1.  Ideally, when the values are above 1, the step size becomes 1. This feature could probably be added to the `_validate_overlap_value`.

**Comment by the-lay** [comment]
And I absolutely love the preview mode that you've done, it's very cool to see the grid change interactively! :)

> Setting the spinbox stepsize to 0.01 is a good idea. I see a bug in this implementation where the up and down arrows won't change the value when the number is > 1. Ideally, when the values are above 1, the step size becomes 1. This feature could probably be added to the `_validate_overlap_value`.

There is something about adaptive step size in qt docs: https://doc.qt.io/qt-5/qdoublespinbox.html#setStepType
I will try it out tomorrow and I will commit it here if it works.

**Comment by the-lay** [comment]
- I've updated to tiler v0.5.0 and use new `tiler.get_all_tiles()` instead of manually gathering tiles
- Adaptive step type seem to work fine, but having preview on around 0.95-1.00 overlap is very laggy (especially on 3D). Maybe it's a good idea to show a confirmation popup on these levels?

**Comment by tdmorello** [comment]
I think the tests will pass if you change [this line](https://github.com/the-lay/napari-tiler/blob/a187521769d4ad40b5a99e4b6a0018489c62903d/src/napari_tiler/_tests/test_dock_widget.py#L163) to `np.testing.assert_almost_equal(image_data, merged_image_data)`

Edit:
I guess I had write access to your fork? I changed that line and will merge now.

**Comment by tdmorello** [comment]
The adaptive step works perfectly for values below 1.0 and above 10. Between 1 and 10, the values increment by 0.1. I think it is going to take a custom solution, but I'd like to merge your changes now and fix that after!

**Pull request merged**
